// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { existsSync } from "node:fs";
import { config as dotenvConfig } from "dotenv";
import { defineConfig } from "prisma";

if (!process.env.DATABASE_URL && existsSync(".env.docker")) {
  dotenvConfig({ path: ".env.docker" });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
